export class GameAudio{
 ctx:AudioContext|null=null;master:GainNode|null=null;musicGain:GainNode|null=null;volume=.35;musicOn=true;effectsOn=true;timer:ReturnType<typeof setInterval>|null=null;step=0;mode='menu';
 unlock(){try{if(!this.ctx){this.ctx=new AudioContext();this.master=this.ctx.createGain();this.master.gain.value=this.volume;this.master.connect(this.ctx.destination);this.musicGain=this.ctx.createGain();this.musicGain.gain.value=.11;this.musicGain.connect(this.master);}if(this.ctx.state==='suspended')void this.ctx.resume();if(!this.timer)this.startMusic(this.mode);}catch{}}
 configure(volume:number,music:boolean,effects:boolean){this.volume=volume;this.musicOn=music;this.effectsOn=effects;if(this.master&&this.ctx)this.master.gain.setTargetAtTime(volume,this.ctx!.currentTime,.05);if(this.musicGain&&this.ctx)this.musicGain.gain.setTargetAtTime(music?.11:0,this.ctx!.currentTime,.15);}
 tone(freq:number,duration:number,type:OscillatorType='sine',gain=.3,slide=0,music=false,delay=0){if(!this.ctx||!this.master||(!music&&!this.effectsOn))return;const t=this.ctx.currentTime+delay,o=this.ctx.createOscillator(),g=this.ctx.createGain();o.type=type;o.frequency.setValueAtTime(freq,t);if(slide)o.frequency.exponentialRampToValueAtTime(Math.max(25,freq+slide),t+duration);g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(Math.max(.001,gain),t+.008);g.gain.exponentialRampToValueAtTime(.0001,t+duration);o.connect(g);g.connect(music?this.musicGain!:this.master);o.start(t);o.stop(t+duration+.03);}
 noise(duration=.12,gain=.18,cutoff=2000){if(!this.ctx||!this.master||!this.effectsOn)return;const n=Math.floor(this.ctx.sampleRate*duration),b=this.ctx.createBuffer(1,n,this.ctx.sampleRate),d=b.getChannelData(0);for(let i=0;i<n;i++)d[i]=(Math.random()*2-1)*(1-i/n);const s=this.ctx.createBufferSource(),f=this.ctx.createBiquadFilter(),g=this.ctx.createGain();s.buffer=b;f.type='lowpass';f.frequency.value=cutoff;g.gain.value=gain;s.connect(f);f.connect(g);g.connect(this.master);s.start();}
 play(kind:string,intensity=1){switch(kind){case 'click':this.tone(600,.045,'sine',.12,150);break;case 'light':this.noise(.10,.17,2000);this.tone(190,.08,'triangle',.14,-100);break;case 'hit':this.noise(.15,.25*intensity,1700);this.tone(100,.16,'sine',.5,-60);break;case 'heavy':this.noise(.24,.26,2400);this.tone(90,.25,'triangle',.45,-60);break;case 'release':this.noise(.20,.23,5500);this.tone(310,.18,'triangle',.20,-210);break;case 'land':this.noise(.25,.24,750);this.tone(65,.23,'sine',.45,-35);break;case 'dash':this.noise(.17,.12,4200);break;case 'block':this.tone(850,.10,'triangle',.22,-500);break;case 'skill':this.tone(200,.32,'sawtooth',.12,550);this.noise(.25,.2,3000);break;case 'ultimate':this.tone(70,1.1,'sawtooth',.15,700);this.tone(110,1.25,'sine',.4,-70);break;case 'box':this.tone(120,.7,'triangle',.25,700);break;case 'reveal':[330,440,554,660,880].forEach((f,i)=>this.tone(f,.6,'triangle',.18,0,false,i*.10));break;case 'victory':[392,494,587,784].forEach((f,i)=>this.tone(f,.45,'triangle',.24,0,false,i*.15));break;case 'defeat':[330,294,247,196].forEach((f,i)=>this.tone(f,.5,'triangle',.15,0,false,i*.18));break;}}
 startMusic(mode:string){this.mode=mode;if(!this.ctx)return;if(this.timer)clearInterval(this.timer);this.step=0;const battle=mode==='battle';this.timer=setInterval(()=>{if(!this.musicOn||!this.ctx||this.ctx.state!=='running')return;const notes=battle?[110,110,130.81,110,164.81,146.83,130.81,98]:[110,164.81,220,196,146.83,220,293.66,196],f=notes[this.step%notes.length];this.tone(f,battle?.23:.7,'triangle',.35,0,true);if(this.step%4===0)this.tone(f/2,battle?.45:1.1,'sine',.5,0,true);if(battle&&this.step%2===0)this.tone(75,.09,'sine',.5,-45,true);this.step++;},battle?230:570);}
 suspend(){if(this.ctx)void this.ctx.suspend();}
 destroy(){if(this.timer)clearInterval(this.timer);this.timer=null;if(this.ctx)void this.ctx.close();this.ctx=null;this.master=null;this.musicGain=null;}
}
export const sound=new GameAudio();
