'use client';
import {assetUrl} from './runtime';
import {Star,Lock,Swords,Diamond,Box,ArrowUpRight} from 'lucide-react';
import {Character,Arena,BoxType,BOXES,RARITY_COLORS,stats,Element,ELEMENT_COLORS} from './data';
import {FighterProgress} from './progression';
import {fighterArt} from './sprites';
export function Portrait({c,className='',style={}}:{c:Character;className?:string;style?:React.CSSProperties}){const art=fighterArt(c.id);return c.portrait>=0?<div role="img" aria-label={c.name} className={`portrait ${className}`} style={{backgroundImage:`url(${assetUrl('/art/portraits.webp')})`,backgroundSize:'500% 300%',backgroundPosition:`${c.portrait%5*25}% ${Math.floor(c.portrait/5)*50}%`,...style}}/>:art?<div className={`portrait sprite-portrait ${className}`} style={{'--element':ELEMENT_COLORS[c.element],...style} as React.CSSProperties}><img src={art.src} alt={c.name} loading="lazy" decoding="async"/></div>:<div className={`portrait ${className}`} role="img" aria-label={`${c.name} artwork unavailable`} style={style}/>;}
export function RarityLabel({c}:{c:Character}){return <span className={`rarity rarity-${c.rarity.toLowerCase()}`} style={{color:RARITY_COLORS[c.rarity]}}><Diamond size={10} fill="currentColor"/>{c.prestige?'DRAGON · ':''}{c.rarity.toUpperCase()}</span>;}
export function FighterCard({c,progress,favorite,selected,onClick,onFavorite}:{c:Character;progress?:FighterProgress;favorite?:boolean;selected?:boolean;onClick:()=>void;onFavorite?:()=>void}){return <article className={`fighter-card ${progress?'owned':'locked'} ${selected?'selected':''} rarity-frame-${c.rarity.toLowerCase()}`} style={{'--rarity':RARITY_COLORS[c.rarity]} as React.CSSProperties}><button className="fighter-card-main" onClick={onClick} aria-label={`Inspect ${c.name}${!progress?', locked':''}`}><div className="fighter-art"><Portrait c={c}/><div className="card-shade"/>{!progress&&<div className="lock-tag"><Lock size={13}/></div>}<span className="fighter-level">{progress?`LV. ${progress.level}`:'LOCKED'}</span></div><div className="fighter-info"><RarityLabel c={c}/><h3>{c.name}</h3><div className="fighter-sub"><span>{c.anime}</span>{progress&&<span><Swords size={12}/>{stats(c,progress.level,progress.mastery).power}</span>}</div></div></button>{onFavorite&&<button className={`favorite ${favorite?'is-favorite':''}`} aria-label={`${favorite?'Unfavorite':'Favorite'} ${c.name}`} onClick={onFavorite}><Star size={15} fill={favorite?'currentColor':'none'}/></button>}</article>;}
export function BoxVisual({type,animated=false}:{type:BoxType|'Dragon';animated?:boolean}){const b=BOXES.find(b=>b.type===type),col=b?.color??'#f9b657';return <div className={`box-visual box-${type.toLowerCase()} ${animated?'charging':''}`} style={{'--box-color':col} as React.CSSProperties}><div className="box-orbit"/><div className="box-orbit second"/><div className="box-sigil">{type==='Dragon'?<Diamond size={66} strokeWidth={1}/>:<Box size={76} strokeWidth={1.1}/>}<span>✦</span></div><div className="box-sparks">{Array.from({length:8},(_,i)=><i key={i} style={{'--i':i} as React.CSSProperties}/>)}</div></div>;}
export function ArenaArt({arena,className=''}:{arena:Arena;className?:string}){return <div role="img" aria-label={`${arena.name} battlefield`} className={`arena-art ${className}`} style={{backgroundImage:`url(${assetUrl(arena.image)})`,backgroundSize:'cover',backgroundPosition:'center'}}/>;}
