import { gameDb } from '@/db/game-db';
import { createPlayer, applyAction, Player } from '@/game/progression';
export const dynamic='force-dynamic';
function identity(req:Request){const user=req.headers.get('oai-authenticated-user-id');if(user)return {id:'user:'+user,cookie:null};const raw=req.headers.get('cookie')?.match(/(?:^|;\s*)aether_session=([a-f0-9-]{36})(?:;|$)/)?.[1];if(raw)return {id:'guest:'+raw,cookie:null};const token=crypto.randomUUID();return {id:'guest:'+token,cookie:`aether_session=${token}; HttpOnly; Path=/; Max-Age=31536000; SameSite=Strict${new URL(req.url).protocol==='https:'?'; Secure':''}`};}
function response(data:unknown,status=200,cookie:string|null=null){const h=new Headers({'Content-Type':'application/json','Cache-Control':'no-store'});if(cookie)h.set('Set-Cookie',cookie);return new Response(JSON.stringify(data),{status,headers:h});}
function safePlayer(p:Player){const {receipts,...rest}=p;return rest;}
async function readOrCreate(id:string){const db=gameDb();let row=await db.prepare('SELECT state, version FROM aether_players WHERE id = ?').bind(id).first<{state:string;version:number}>();if(!row){const p=createPlayer();await db.prepare('INSERT OR IGNORE INTO aether_players (id,state,version,updated_at) VALUES (?,?,0,?)').bind(id,JSON.stringify(p),Date.now()).run();row=await db.prepare('SELECT state, version FROM aether_players WHERE id = ?').bind(id).first<{state:string;version:number}>();}if(!row)throw new Error('Your save could not be loaded. Please retry.');return {p:JSON.parse(row.state) as Player,version:row.version};}
export async function GET(req:Request){const who=identity(req);try{const {p}=await readOrCreate(who.id);return response({player:safePlayer(p)},200,who.cookie);}catch(e){console.error('game-load',e);return response({error:'Your progress could not be loaded. Please retry; your saved data has not been reset.'},503);}}
export async function POST(req:Request){const who=identity(req);try{const origin=req.headers.get('origin');if(origin&&origin!==new URL(req.url).origin)return response({error:'Please perform this action from the game.'},403);if(!req.headers.get('content-type')?.includes('application/json'))return response({error:'Invalid request.'},415);const raw=await req.text();if(raw.length>16000)return response({error:'Request too large.'},413);const data=JSON.parse(raw);if(typeof data.requestId!=='string'||data.requestId.length>80)return response({error:'A request identifier is required.'},400);const {p,version}=await readOrCreate(who.id);if(p.receipts[data.requestId])return response({player:safePlayer(p),result:p.receipts[data.requestId]},200,who.cookie);let result;try{result=applyAction(p,data.action,data,()=>crypto.getRandomValues(new Uint32Array(1))[0]/4294967296);}catch(e){return response({error:e instanceof Error?e.message:'This action could not be completed.',player:safePlayer((await readOrCreate(who.id)).p)},400,who.cookie);}p.version=version+1;p.receipts[data.requestId]=result;const keys=Object.keys(p.receipts);keys.slice(0,Math.max(0,keys.length-30)).forEach(k=>delete p.receipts[k]);const saved=await gameDb().prepare('UPDATE aether_players SET state = ?, version = ?, updated_at = ? WHERE id = ? AND version = ?').bind(JSON.stringify(p),p.version,Date.now(),who.id,version).run();if(!saved.meta.changes)return response({error:'Your progress changed in another tab. Please try this action again.',player:safePlayer((await readOrCreate(who.id)).p)},409,who.cookie);return response({player:safePlayer(p),result},200,who.cookie);}catch(e){console.error('game-save',e);return response({error:'Your save is temporarily unavailable. Retry this action when connected.'},503,who.cookie);}}
